In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ydata_profiling as yp
import warnings
warnings.filterwarnings("ignore")

c:\Users\DELL\Desktop\ML Projects\Real_Estate\project\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Read dataset

In [2]:
df = pd.read_csv(r'../data/raw/Real_Estate.csv')
df.head()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...

In [ ]:
df.info()

In [122]:
df.describe()

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,price_in_USD
count,64719.000000,68224.000000,54592.000000,74178.000000,36982.000000,55973.000000,1.449610e+05
mean,1996.921754,8.575692,5.791709,2.572097,2.289222,1.364229,4.121722e+05
std,157.527635,8.356781,5.541368,1.319545,18.276913,0.745019,8.420984e+05
min,1.000000,-1.000000,-2.000000,-1.000000,-1.000000,1.000000,0.000000e+00
25%,2004.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.054200e+05
50%,2021.000000,5.000000,4.000000,2.000000,2.000000,1.000000,1.902120e+05
75%,2024.000000,14.000000,8.000000,3.000000,3.000000,2.000000,3.989300e+05
max,2316.000000,124.000000,202.000000,124.000000,2009.000000,43.000000,3.060283e+07

In [123]:
df.duplicated().sum()

np.int64(0)

In [ ]:
profile = yp.ProfileReport(df)
profile.to_file("real_estate_report_before_cleaning.html")

100%|██████████| 14/14 [00:07<00:00,  1.95it/s]7<00:03,  1.38it/s, Describe variable: url]
Summarize dataset: 100%|██████████| 73/73 [00:16<00:00,  4.44it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.03s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.76s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 30.07it/s]

In [124]:
df.isnull().sum()

title                              0
country                          130
location                         131
building_construction_year     82817
building_total_floors          79312
apartment_floor                92944
apartment_rooms                73358
apartment_bedrooms            110554
apartment_bathrooms            91563
apartment_total_area            5740
apartment_living_area         119824
price_in_USD                    2575
image                              0
url                                0
dtype: int64

# Some Feature Engineering

In [125]:
rows_with_null_title_or_country = df[df[['title', 'country']].isnull().any(axis=1)]
rows_with_null_title_or_country

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
3772,"3 room apartment 180 m² in, Turkey",NaN,NaN,NaN,3.0,NaN,4.0,3.0,NaN,180 m²,NaN,528267.0,https://realting.com/uploads/bigSlider/192/45f...,https://realting.com/property-for-sale/turkey/...
3775,"3 room apartment 160 m² in, Turkey",NaN,NaN,NaN,3.0,NaN,4.0,3.0,NaN,160 m²,NaN,647699.0,https://realting.com/uploads/bigSlider/f05/5fa...,https://realting.com/property-for-sale/turkey/...
3863,"4 room apartment 165 m² in, Turkey",NaN,NaN,2023.0,5.0,2.0,5.0,4.0,3.0,165 m²,157 m²,581507.0,https://realting.com/uploads/bigSlider/ef2/9a3...,https://realting.com/property-for-sale/turkey/...
3936,"3 room apartment 350 m² in, Turkey",NaN,NaN,NaN,3.0,NaN,4.0,3.0,NaN,350 m²,NaN,809624.0,https://realting.com/uploads/bigSlider/827/3d8...,https://realting.com/property-for-sale/turkey/...
4132,"3 room apartment 254 m² in, Turkey",NaN,NaN,NaN,4.0,NaN,4.0,3.0,NaN,254 m²,NaN,755649.0,https://realting.com/uploads/bigSlider/808/01a...,https://realting.com/property-for-sale/turkey/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142504,"3 room apartment 160 m² in, Italy",NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,160 m²,NaN,765071.0,https://realting.com/uploads/bigSlider/530/8ca...,https://realting.com/property-for-sale/italy/r...
142923,"3 room apartment 103 m² in, Greece",NaN,NaN,2023.0,1.0,1.0,4.0,3.0,1.0,103 m²,NaN,382535.0,https://realting.com/uploads/bigSlider/836/9d4...,https://realting.com/property-for-sale/greece/...
144095,"1 room apartment 54 m² in, Greece",NaN,NaN,NaN,7.0,NaN,2.0,1.0,NaN,54 m²,NaN,244830.0,https://realting.com/uploads/bigSlider/9bf/9ce...,https://realting.com/property-for-sale/greece/...
144103,"3 room apartment 150 m² in, Greece",NaN,NaN,1980.0,1.0,3.0,4.0,3.0,2.0,150 m²,NaN,273240.0,https://realting.com/uploads/bigSlider/8ee/666...,https://realting.com/property-for-sale/greece/...
144337,"1 room apartment 55 m² in, Turkey",NaN,NaN,2023.0,3.0,2.0,2.0,1.0,1.0,55 m²,50 m²,278704.0,https://realting.com/uploads/bigSlider/98c/ed0...,https://realting.com/property-for-sale/turkey/...

### We extract country from title by REGEX

In [126]:
import re
def extract_country_from_title_end(title: str):
    if pd.isna(title):
        return np.nan
    t = str(title).strip()
    if ',' in t:
        last_seg = t.split(',')[-1].strip()
        last_seg = re.sub(r'[\(\)\[\]]', '', last_seg).strip()
        if re.search(r'[A-Za-z]', last_seg):
            return last_seg.title()
    m = re.search(r'\bin\s+([A-Za-z]+(?:\s+[A-Za-z]+)*)\s*$', t, flags=re.IGNORECASE)
    if m:
        return m.group(1).title()
    m2 = re.search(r'([A-Za-z]+(?:\s+[A-Za-z]+)*)\s*$', t)
    if m2:
        candidate = m2.group(1).strip().title()
        if re.search(r'[A-Za-z]', candidate) and not re.search(r'\d', candidate):
            return candidate
    return np.nan


df['country_from_title'] = df['title'].apply(extract_country_from_title_end)
df['country'] = df['country'].fillna(df['country_from_title'])
print(df[['title', 'country']].head(10))

                                               title     country
0  2 room apartment 120 m² in Mediterranean Regio...      Turkey
1              4 room villa 500 m² in Kalkan, Turkey      Turkey
2          1 room apartment 65 m² in Antalya, Turkey      Turkey
3             1 room apartment  in Pattaya, Thailand    Thailand
4             2 room apartment  in Pattaya, Thailand    Thailand
5          1 room apartment 28 m² in Batumi, Georgia     Georgia
6        4 room apartment 245 m² in Yesiloez, Turkey      Turkey
7      1 room studio apartment  in Pattaya, Thailand    Thailand
8  Apartment 1 bathroom 74 m² in Ratisevina-Susce...  Montenegro
9       1 room apartment 50 m² in Becici, Montenegro  Montenegro

In [127]:
df["country"].isnull().sum()

np.int64(0)

In [128]:
df.location.isnull().sum()

np.int64(131)

In [129]:
df.dropna(subset=['location'], inplace=True)

In [130]:
df = df.drop(columns=['country_from_title'])

### Remove any string from (apartment_total_area) && (apartment_living_area)

In [131]:
import re
def to_float_m2(x):
    if pd.isna(x):
        return np.nan
    s = str(x).lower().strip()
    s = re.sub(r'(m²|㎡|m2|sq\.?\s*m|square\s*meters?)', '', s, flags=re.IGNORECASE)
    s = re.sub(r'[^0-9,.\-]', ' ', s)
    s = s.replace(',', '.')
    m = re.search(r'(-?\d+(?:\.\d+)?)', s)
    return float(m.group(1)) if m else np.nan

df['apartment_total_area'] = df['apartment_total_area'].apply(to_float_m2)
df['apartment_living_area'] = df['apartment_living_area'].apply(to_float_m2)

In [132]:
df[['apartment_total_area', 'apartment_living_area']]

        apartment_total_area  apartment_living_area
0                      120.0                  110.0
1                      500.0                  480.0
2                       65.0                   60.0
3                        NaN                   40.0
4                        NaN                   36.0
...                      ...                    ...
147531                 310.0                    NaN
147532                 192.0                  151.0
147533                   NaN                   84.0
147534                   NaN                    NaN
147535                 140.0                    NaN

[147405 rows x 2 columns]

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147405 entries, 0 to 147535
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       147405 non-null  object
 1   country                     147405 non-null  object
 2   location                    147405 non-null  object
 3   building_construction_year  64629 non-null   float64
 4   building_total_floors       68119 non-null   float64
 5   apartment_floor             54513 non-null   float64
 6   apartment_rooms             74086 non-null   float64
 7   apartment_bedrooms          36935 non-null   float64
 8   apartment_bathrooms         55917 non-null   float64
 9   apartment_total_area        141667 non-null  float64
 10  apartment_living_area       27648 non-null   float64
 11  price_in_USD                144830 non-null  float64
 12  image                       147405 non-null  object
 13  url                         147405 non-null  object
dtypes: float64(9), object(5)
memory usage: 16.9+ MB

### Note the title exist at the first statement number , This number related to (apartment_bedrooms) column

In [134]:
def extract_bedrooms(title):
    if pd.isna(title):
        return np.nan
    t = str(title).lower()
    m = re.search(r'(\d+)\s*(bedroom|bed)', t)
    if m:
        return float(m.group(1))
    m2 = re.search(r'(\d+)\s*\+\s*(\d+)', t)
    if m2:
        first = int(m2.group(1))
        second = int(m2.group(2))
        return 0.0 if (first == 1 and second == 0) else float(first)
    if 'studio' in t:
        return 0.0
    m3 = re.search(r'(\d+)\s*room', t)
    if m3:
        return float(m3.group(1)) 
    return np.nan


df['apartment_bedrooms_from_title'] = df['title'].apply(extract_bedrooms)
df['apartment_bedrooms'] = df['apartment_bedrooms'].fillna(df['apartment_bedrooms_from_title'])

In [137]:
df.apartment_bedrooms.isnull().sum()

np.int64(21816)

In [138]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147405 entries, 0 to 147535
Data columns (total 15 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   title                          147405 non-null  object
 1   country                        147405 non-null  object
 2   location                       147405 non-null  object
 3   building_construction_year     64629 non-null   float64
 4   building_total_floors          68119 non-null   float64
 5   apartment_floor                54513 non-null   float64
 6   apartment_rooms                74086 non-null   float64
 7   apartment_bedrooms             125589 non-null  float64
 8   apartment_bathrooms            55917 non-null   float64
 9   apartment_total_area           141667 non-null  float64
 10  apartment_living_area          27648 non-null   float64
 11  price_in_USD                   144830 non-null  float64
 12  image                          147405 non-null  object
 13  url                            147405 non-null  object
 14  apartment_bedrooms_from_title  125552 non-null  float64
dtypes: float64(10), object(5)
memory usage: 18.0+ MB

In [139]:
df = df.drop(columns=['apartment_bedrooms_from_title'] , axis=1)

In [140]:
df.dropna(subset=['price_in_USD' , 'apartment_total_area'], inplace=True)

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 140126 entries, 0 to 147535
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       140126 non-null  object
 1   country                     140126 non-null  object
 2   location                    140126 non-null  object
 3   building_construction_year  62222 non-null   float64
 4   building_total_floors       66655 non-null   float64
 5   apartment_floor             53643 non-null   float64
 6   apartment_rooms             72634 non-null   float64
 7   apartment_bedrooms          121125 non-null  float64
 8   apartment_bathrooms         54472 non-null   float64
 9   apartment_total_area        140126 non-null  float64
 10  apartment_living_area       25596 non-null   float64
 11  price_in_USD                140126 non-null  float64
 12  image                       140126 non-null  object
 13  url                         140126 non-null  object
dtypes: float64(9), object(5)
memory usage: 16.0+ MB

In [142]:
for col in df.columns:
    print(f"{col}: {df[col].value_counts()} ")
    print("-" * 50)

title: title
1 room apartment 24 m² in poselenie Sosenskoe, Russia      486
2 room apartment 40 m² in poselenie Sosenskoe, Russia      369
1 room apartment 24 m² in Kommunarka, Russia               343
1 room apartment 21 m² in poselenie Sosenskoe, Russia      332
1 room apartment 23 m² in poselenie Sosenskoe, Russia      296
                                                          ...
3 room apartment 66 m² in Riga, Latvia                       1
4 room apartment 234 m² in Jurmala, Latvia                   1
2 room apartment 165 m² in Jurmala, Latvia                   1
Apartment 2 bathrooms 49 m² in Debreceni jaras, Hungary      1
1 room apartment 23 m² in Bangkok, Thailand                  1
Name: count, Length: 75159, dtype: int64
--------------------------------------------------
country: country
Turkey             23959
Hungary            22312
Russia             18474
Spain              14231
Belarus            13626
Greece             11618
Montenegro          9906
Georgia             3263
Italy               2869
UAE                 2570
Lithuania           2553
Latvia              2281
Uzbekistan          1945
Portugal            1880
Thailand            1864
Croatia             1831
Czech Republic      1358
Poland              1205
Finland              762
Northern Cyprus      624
United States        413
Austria              198
Armenia              110
Serbia               104
Indonesia             99
Cyprus                70
Australia              1
Name: count, dtype: int64
--------------------------------------------------
location: location
Mediterranean Region, Sekerhane Mahallesi, Alanya, Turkey                                                7062
Central Federal District, poselenie Sosenskoe, Novomoskovsky Administrative Okrug, Russia                7023
Central Hungary, Budapest, Komarom-Esztergom, Hungary                                                    4365
Minsk, Belarus                                                                                           4224
Kommunarka, Central Federal District, poselenie Sosenskoe, Novomoskovsky Administrative Okrug, Russia    2681
                                                                                                         ...
Rogac, Split-Dalmatia County, Croatia                                                                       1
Icici, Opatija, Grad Opatija, Primorje-Gorski Kotar County, Croatia                                         1
Donja Pusca, Opcina Pusca, Zagreb County, Croatia                                                           1
Svirce, Opcina Jelsa, Split-Dalmatia County, Croatia                                                        1
Pecatu, Kuta Selatan, Indonesia                                                                             1
Name: count, Length: 7008, dtype: int64
--------------------------------------------------
building_construction_year: building_construction_year
2023.0    8541
2025.0    8424
2024.0    5731
2026.0    4465
2022.0    3531
          ...
1822.0       1
20.0         1
29.0         1
1740.0       1
202.0        1
Name: count, Length: 224, dtype: int64
--------------------------------------------------
building_total_floors: building_total_floors
 1.0      9908
 2.0      7917
 5.0      6169
 3.0      5904
 4.0      4393
          ...
 72.0        1
 58.0        1
 115.0       1
 61.0        1
-1.0         1
Name: count, Length: 86, dtype: int64
--------------------------------------------------
apartment_floor: apartment_floor
1.0      9083
2.0      7784
3.0      6738
4.0      5301
5.0      4374
         ...
55.0        1
62.0        1
58.0        1
202.0       1
66.0        1
Name: count, Length: 70, dtype: int64
--------------------------------------------------
apartment_rooms: apartment_rooms
 2.0      25035
 3.0      22949
 1.0      11980
 4.0       9363
 5.0       2399
 6.0        590
 7.0        133
 8.0         69
-1.0         32
 9.0         24
 10.0        17
 12.0         8
 11.0         7
 18.0         4
 14.0         3
 13.0         3
 35.0         2
 16.0         2
 22.0         1
 19.0         1
 41.0         1
 21.0         1
 24.0         1
 30.0         1
 20.0         1
 124.0        1
 15.0         1
 57.0         1
 25.0         1
 50.0         1
 55.0         1
 17.0         1
Name: count, dtype: int64
--------------------------------------------------
apartment_bedrooms: apartment_bedrooms
 2.0       36330
 3.0       34079
 1.0       20592
 4.0       16224
 5.0        7114
 6.0        2984
 7.0        1245
 9.0         996
 8.0         749
 0.0         687
-1.0          37
 10.0         31
 12.0         15
 11.0         10
 14.0          7
 13.0          3
 15.0          3
 16.0          3
 35.0          2
 45.0          1
 55.0          1
 500.0         1
 2009.0        1
 24.0          1
 17.0          1
 2004.0        1
 43.0          1
 70.0          1
 25.0          1
 27.0          1
 41.0          1
 2006.0        1
 20.0          1
Name: count, dtype: int64
--------------------------------------------------
apartment_bathrooms: apartment_bathrooms
1.0     38873
2.0     13088
3.0      1780
4.0       477
5.0       119
6.0        66
7.0        20
10.0       12
8.0        12
9.0         6
14.0        4
11.0        4
17.0        3
21.0        2
13.0        2
12.0        1
30.0        1
43.0        1
27.0        1
Name: count, dtype: int64
--------------------------------------------------
apartment_total_area: apartment_total_area
100.0    2446
60.0     2410
50.0     2239
55.0     2094
120.0    2083
         ...
508.0       1
701.0       1
723.0       1
897.0       1
821.0       1
Name: count, Length: 898, dtype: int64
--------------------------------------------------
apartment_living_area: apartment_living_area
30.0     877
17.0     685
28.0     632
32.0     618
29.0     595
        ...
580.0      1
311.0      1
319.0      1
617.0      1
451.0      1
Name: count, Length: 489, dtype: int64
--------------------------------------------------
price_in_USD: price_in_USD
380425.0    490
489118.0    409
326078.0    406
347817.0    352
271732.0    346
           ...
242970.0      1
813839.0      1
834927.0      1
292000.0      1
168039.0      1
Name: count, Length: 47652, dtype: int64
--------------------------------------------------
image: image
https://realting.com/uploads/bigSlider/9b9/e2ba64b16cdd1fd0bb86dcbd1b5fb.webp    1219
https://realting.com/main/images/no-image.png                                     691
https://realting.com/uploads/bigSlider/3f6/01a3dcc54ec83.webp                     678
https://realting.com/uploads/bigSlider/3c5/2bee197adb3f9d328e3813ac346cb.webp     608
https://realting.com/uploads/bigSlider/591/61e3da5935315c2b0cc2f8d52a7da.webp     601
                                                                                 ...
https://realting.com/uploads/bigSlider/2f4/e6ee950a8b17036b15e71b05d8be8.webp       1
https://realting.com/uploads/bigSlider/969/0ddb85a97317.webp                        1
https://realting.com/uploads/bigSlider/8b5/9b4e09b9cc991.webp                       1
https://realting.com/uploads/bigSlider/aa0/a955417dc5081a3c1c639484b009e.webp       1
https://realting.com/uploads/bigSlider/fab/0eb4129435d4e70d8cd24cc5d762b.webp       1
Name: count, Length: 106994, dtype: int64
--------------------------------------------------
url: url
https://realting.com/property-for-sale/turkey/inest-homes/1766770             1
https://realting.com/property-for-sale/turkey/inest-homes/1767446             1
https://realting.com/property-for-sale/turkey/fsbo/1766776                    1
https://realting.com/property-for-sale/georgia/flatiko-llc/1765932            1
https://realting.com/property-for-sale/turkey/fsbo/1732620                    1
                                                                             ..
https://realting.com/property-for-sale/turkey/ip-puh-elena-yurevna/1721363    1
https://realting.com/property-for-sale/turkey/deniz-estate/1634645            1
https://realting.com/property-for-sale/turkey/deniz-estate/1664783            1
https://realting.com/property-for-sale/turkey/tekce-overseas/1726683          1
https://realting.com/property-for-sale/turkey/tranio/1752653                  1
Name: count, Length: 140126, dtype: int64
--------------------------------------------------

In [143]:
df.drop(columns=['image' , 'url' , 'title'], inplace=True)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 140126 entries, 0 to 147535
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   country                     140126 non-null  object
 1   location                    140126 non-null  object
 2   building_construction_year  62222 non-null   float64
 3   building_total_floors       66655 non-null   float64
 4   apartment_floor             53643 non-null   float64
 5   apartment_rooms             72634 non-null   float64
 6   apartment_bedrooms          121125 non-null  float64
 7   apartment_bathrooms         54472 non-null   float64
 8   apartment_total_area        140126 non-null  float64
 9   apartment_living_area       25596 non-null   float64
 10  price_in_USD                140126 non-null  float64
dtypes: float64(9), object(2)
memory usage: 12.8+ MB

### Remove Outliers

In [ ]:
def remove_outliers(df):
    q1 = df.quantile(0.25)
    q3 = df.quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - (1.5 * iqr)
    upper_bound = q3 + (1.5 * iqr)
    return df[(df > lower_bound) & (df < upper_bound)]

df['building_construction_year'] = remove_outliers(df['building_construction_year'])
df['building_total_floors'] = remove_outliers(df['building_total_floors'])
df['apartment_floor'] = remove_outliers(df['apartment_floor'])
df['apartment_rooms'] = remove_outliers(df['apartment_rooms'])
df['apartment_bedrooms'] = remove_outliers(df['apartment_bedrooms'])
df

,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD
0,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120.0,110.0,315209.0
1,Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,4.0,NaN,500.0,480.0,1108667.0
2,Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65.0,60.0,173211.0
5,Georgia,"Abkhazia, Batumi, Georgia",2026.0,NaN,NaN,1.0,1.0,1.0,28.0,NaN,35622.0
6,Turkey,"Yesiloez, Mediterranean Region, Alanya, Turkey",2007.0,2.0,3.0,NaN,4.0,4.0,245.0,245.0,274415.0
...,...,...,...,...,...,...,...,...,...,...,...
147529,Turkey,"Yaylali, Mediterranean Region, Alanya, Turkey",2023.0,NaN,NaN,3.0,3.0,1.0,106.0,NaN,510856.0
147530,Turkey,"Bahcelievler Mahallesi, Marmara Region, Turkey",NaN,NaN,NaN,NaN,3.0,NaN,168.0,NaN,614848.0
147531,Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,NaN,NaN,310.0,NaN,597810.0
147532,Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,NaN,4.0,2.0,192.0,151.0,637195.0
147535,Turkey,Turkey,NaN,2.0,NaN,NaN,4.0,NaN,140.0,NaN,939164.0

In [146]:
df.describe()

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD
count,56103.000000,65675.000000,51496.000000,69327.000000,107225.000000,54472.000000,140126.000000,25596.000000,1.401260e+05
mean,2015.554445,8.052745,5.079132,2.428332,2.428398,1.359028,126.011511,68.722496,4.019648e+05
std,13.633776,6.940830,3.999365,0.927683,0.965188,0.742516,117.501552,74.050034,8.175746e+05
min,1972.000000,-1.000000,-2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000e+00
25%,2011.000000,2.000000,2.000000,2.000000,2.000000,1.000000,56.000000,30.000000,1.041075e+05
50%,2022.000000,5.000000,4.000000,2.000000,2.000000,1.000000,87.000000,44.000000,1.870680e+05
75%,2024.000000,13.000000,7.000000,3.000000,3.000000,2.000000,150.000000,80.000000,3.912940e+05
max,2028.000000,31.000000,16.000000,4.000000,4.000000,43.000000,998.000000,999.000000,3.060283e+07

### Clean this columns , It's not logic

In [147]:
df.drop(df[df['building_total_floors'] < 0].index, inplace=True)
df.drop(df[df['apartment_rooms'] < 0].index, inplace=True)
df.drop(df[df['apartment_floor'] < 0].index, inplace=True)
df.drop(df[df['apartment_bedrooms'] < 0].index, inplace=True)
df.drop(df[df['building_construction_year'] > 2025].index, inplace=True)
df

,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD
0,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120.0,110.0,315209.0
1,Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,4.0,NaN,500.0,480.0,1108667.0
2,Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65.0,60.0,173211.0
6,Turkey,"Yesiloez, Mediterranean Region, Alanya, Turkey",2007.0,2.0,3.0,NaN,4.0,4.0,245.0,245.0,274415.0
8,Montenegro,"Ratisevina-Suscepan-Trebesin, Herceg Novi, Mon...",NaN,NaN,NaN,NaN,NaN,1.0,74.0,NaN,168881.0
...,...,...,...,...,...,...,...,...,...,...,...
147529,Turkey,"Yaylali, Mediterranean Region, Alanya, Turkey",2023.0,NaN,NaN,3.0,3.0,1.0,106.0,NaN,510856.0
147530,Turkey,"Bahcelievler Mahallesi, Marmara Region, Turkey",NaN,NaN,NaN,NaN,3.0,NaN,168.0,NaN,614848.0
147531,Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,NaN,NaN,310.0,NaN,597810.0
147532,Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,NaN,4.0,2.0,192.0,151.0,637195.0
147535,Turkey,Turkey,NaN,2.0,NaN,NaN,4.0,NaN,140.0,NaN,939164.0

In [148]:
df.describe()

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD
count,51430.000000,61274.000000,47040.000000,64733.000000,102377.000000,50023.000000,135060.000000,25418.000000,1.350600e+05
mean,2014.609333,7.573587,4.874320,2.451377,2.442805,1.385663,128.131897,68.694350,4.070674e+05
std,13.849518,6.834394,3.877449,0.919757,0.960639,0.765675,118.209400,74.020362,8.200293e+05
min,1972.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000e+00
25%,2009.000000,2.000000,2.000000,2.000000,2.000000,1.000000,58.000000,30.000000,1.048792e+05
50%,2022.000000,5.000000,4.000000,2.000000,2.000000,1.000000,90.000000,44.000000,1.926660e+05
75%,2024.000000,12.000000,7.000000,3.000000,3.000000,2.000000,150.000000,80.000000,3.978160e+05
max,2025.000000,31.000000,16.000000,4.000000,4.000000,43.000000,998.000000,999.000000,3.060283e+07

In [149]:
df.isnull().sum()

country                            0
location                           0
building_construction_year     83630
building_total_floors          73786
apartment_floor                88020
apartment_rooms                70327
apartment_bedrooms             32683
apartment_bathrooms            85037
apartment_total_area               0
apartment_living_area         109642
price_in_USD                       0
dtype: int64

### Filling missing values

In [150]:
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
X = df.drop(columns=['price_in_USD'])
y = df['price_in_USD']
num_cols = X.select_dtypes(include=['float64', 'int64']).columns

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42 , shuffle=True
)
X_train

,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area
136888,Italy,"Abruzzo, Pescara, Italy",NaN,NaN,NaN,NaN,3.0,NaN,180.0,NaN
7495,Turkey,"Mahmutlar, Mediterranean Region, Alanya, Turkey",2018.0,5.0,5.0,2.0,1.0,NaN,60.0,NaN
97941,Spain,"Valencian Community, el Poble Nou de Benitatxe...",NaN,NaN,NaN,NaN,1.0,1.0,45.0,NaN
90456,Belarus,"Minsk Region, Bialarucki sielski Saviet, Lahoy...",2012.0,NaN,NaN,NaN,NaN,NaN,64.0,58.0
62059,Russia,"Central Federal District, poselenie Sosenskoe,...",2024.0,16.0,8.0,3.0,3.0,1.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
119692,Poland,"Masovian Voivodeship, Warsaw, Poland",NaN,4.0,4.0,4.0,3.0,2.0,143.0,NaN
130333,UAE,"Sharjah Emirate, Sharjah, UAE",NaN,NaN,NaN,1.0,1.0,2.0,695.0,NaN
112869,Montenegro,Montenegro,NaN,NaN,NaN,NaN,3.0,NaN,160.0,NaN
144115,Serbia,"Central Serbia, Belgrade, City of Belgrade, Se...",NaN,4.0,3.0,2.0,1.0,1.0,52.0,NaN
132723,UAE,"Dubai, UAE",2025.0,NaN,NaN,1.0,1.0,NaN,38.0,NaN

In [153]:
imputer = KNNImputer(
    n_neighbors=2,      
    weights='distance'
)
X_train[num_cols] = imputer.fit_transform(X_train[num_cols])
X_test[num_cols]  = imputer.transform(X_test[num_cols])
print('KNN Imputetion Done!')

KNN Imputetion Done!

In [156]:
X_train.isnull().sum()

country                       0
location                      0
building_construction_year    0
building_total_floors         0
apartment_floor               0
apartment_rooms               0
apartment_bedrooms            0
apartment_bathrooms           0
apartment_total_area          0
apartment_living_area         0
dtype: int64

In [158]:
X_test.isnull().sum()

country                       0
location                      0
building_construction_year    0
building_total_floors         0
apartment_floor               0
apartment_rooms               0
apartment_bedrooms            0
apartment_bathrooms           0
apartment_total_area          0
apartment_living_area         0
dtype: int64

In [160]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108048 entries, 136888 to 132723
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   country                     108048 non-null  object
 1   location                    108048 non-null  object
 2   building_construction_year  108048 non-null  float64
 3   building_total_floors       108048 non-null  float64
 4   apartment_floor             108048 non-null  float64
 5   apartment_rooms             108048 non-null  float64
 6   apartment_bedrooms          108048 non-null  float64
 7   apartment_bathrooms         108048 non-null  float64
 8   apartment_total_area        108048 non-null  float64
 9   apartment_living_area       108048 non-null  float64
dtypes: float64(8), object(2)
memory usage: 9.1+ MB

In [ ]:
train = pd.concat([X_train, y_train], axis=1)
train.to_csv('../data/processed/train.csv', index=False)

In [ ]:
test = pd.concat([X_test, y_test], axis=1)
test.to_csv('../data/processed/test.csv', index=False)

In [167]:
all_data = pd.concat([train, test], axis=0)
all_data.to_csv('../data/processed/all_data.csv', index=False)

In [168]:
profile_2 = all_data.profile_report()
profile_2.to_file(output_file="all_data.html")

100%|██████████| 11/11 [00:01<00:00,  9.30it/s]1<00:00,  5.97it/s, Describe variable: price_in_USD]
Summarize dataset: 100%|██████████| 101/101 [00:27<00:00,  3.62it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.42s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.23s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]